### PR TITLE
Only update the names matched if a line is matched successfully.

### PR DESCRIPTION
**Pull request by ltratt**
Bug found by Edd Barrett.

### CODE REVIEW

**Comment by vext01** [comment]
Great, thanks!

bors r+

**Comment by vext01** [comment]
```
187 |     fn version(&self) -> &semver::Version {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `semver::version::Version`, found a different struct `semver::version::Version`
    |
    = note: expected fn pointer `fn(&Krate) -> &semver::version::Version` (struct `semver::version::Version`)
               found fn pointer `fn(&Krate) -> &semver::version::Version` (struct `semver::version::Version`)
    = note: perhaps two different versions of crate `semver` are being used?
```

Uh...

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
@vext01 See if that new commit makes sense to you (the problem is that "cargo deny" isn't currently building properly... but with "set -e" we have to be a bit cunning with what to do with commands-that-can-exit).

**Comment by vext01** [comment]
K, squash it in!

**Comment by ltratt** [comment]
No, it shouldn't be squashed.

**Pull request merged**
