### PR TITLE
Prepare a 0.1.0 release.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
That second commit will need squashing.

**Comment by ltratt** [comment]
OK to squash?

**Comment by vext01** [comment]
Thanks for that!

Please squash.

**Comment by ltratt** [comment]
Squashed.

**Comment by vext01** [comment]
It's a `cargo fmt` issue:
```
+ cargo fmt --all -- --check
Diff in /home/buildbot-worker1/worker1/buildbot-build-script/build/src/lib.rs at line 47:
 /// assert!(matcher.matches("a a").is_ok());
 /// assert!(matcher.matches("a b").is_err());
 /// ```
-
 use std::{
     collections::hash_map::{Entry, HashMap},
     default::Default,
```

**Comment by ltratt** [comment]
Fixed in https://github.com/softdevteam/fm/pull/13/commits/10b0a26a81bd18b872670898eb9e08ab595c3bb7.

**Comment by vext01** [comment]
Please squash

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
