### PR TITLE
Fix error line

### LINKED ISSUE #5: Incorrect error line?
I added the test:
```
assert_eq!(helper("...\nline2\nline3\nline4\n", "line1\nline2\nline3\nbadgers\nline5"), 4);
```

Which gives fails, as the failure line reported is `3`, not as I expected `4`. I expected `4` because the first line in the text which doesn't match is `badgers` on line 4.

Did I misunderstand something, or is that a bug?

### PR DESCRIPTION
**Pull request by ltratt**
Fixes https://github.com/softdevteam/fm/issues/5.

### CODE REVIEW

**Comment by ltratt** [comment]
I jumped the gun. Needs https://github.com/softdevteam/fm/pull/4 to be merged first.

**Comment by vext01** [comment]
Looks good. Waiting for #4...

**Comment by ltratt** [comment]
OK for me to rebase against master when #4 merges?

**Comment by vext01** [comment]
By all means!

**Comment by ltratt** [comment]
Rebased against master.

**Pull request merged**
