### PR TITLE
Intra-line wildcards and name matching can't mix without causing backtracking

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by vext01** [comment]
Interesting.

Could the rule be relaxed a little by allowing `...` and `$x` on the same line, just not adjacent.

E.g. in `...a$1` the `a` anchors the `...` meaning that backtracking isn't required (so long as we assume the first `a` is always matched).

I may be wrong.

**Comment by ltratt** [comment]
Could it be relaxed? Maybe. But let's see if we can get away without the complexity.

**Comment by vext01** [comment]
(I've also added the required status checks in the repo settings)

**Comment by ltratt** [comment]
> (I've also added the required status checks in the repo settings)

Aha, good thinking!

**Pull request merged**
