### PR TITLE
Stop Clippy complaining that FMOptions isn't camel case.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by vext01** [comment]
Are you happy to apply that rule to the whole module, or did you only want it on that one struct?

**Comment by ltratt** [comment]
I think the lint is asinine, so I'm happy to apply it globally.

**Comment by vext01** [comment]
I'm not sure if that annotation is global or just the module, but I'll leave that up to you to look into.

bors r+

**Comment by ltratt** [comment]
It's global to the crate.

**Comment by vext01** [comment]
Needs rustfmt

**Comment by vext01** [comment]
Don't forget this PR :)

**Comment by ltratt** [comment]
Oops! Fixed in https://github.com/softdevteam/fm/pull/28/commits/13c159dfbc748948d5c27201caec33a7a4c2e3ef.

**Comment by vext01** [comment]
Please squash.

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
